name = 'pixelbrush'
compatibility_date = "2024-12-01"

[assets]
directory = "out"

[[routes]]
pattern = "pixelbru.sh/*"
custom_domain = true

[[routes]]
pattern = "www.pixelbru.sh/*"
custom_domain = true
