import IconCloud from "~/components/ui/icon-cloud"

const SKILLS_SLUGS = [
    "go",
    "rust",
    "javascript",
    "typescript",
    "tailwind css",
    "git",
    "solid",
    "react",
    "next.js",
    "amazon eks",
    "aws lambda",
    "aws fargate",
    "aws secrets manager",
    "aws elastic load balancing",
    "amazon web services",
    "amazon route 53",
    "amazon dynamodb",
    "amazon cloudwatch",
    "amazon sqs",
    "amazon elasticache",
    ".net",
    ".env",
    "graphql",
    "json",
    "ts-node",
    "helix",
    "amazon rds",
    "app store",
    "sqlite",
    "toml",
    "npm",
    "podman",
    "node.js",
    "serverless",
    "amazon web services",
    "jira software",
    "caddy",
    "vitest",
    "prettier",
    "liquibase",
    "kubernetes",
    "auth0",
    "linear",
    "bitbucket",
    "hugging face",
    "github",
    "amazon s3",
    "dart",
    "json web tokens",
    "amazon ecs",
    "i18next",
    "webpack",
    "react hook form",
    "gitlab",
    "linux",
    "supabase",
    "amazon api gateway",
    "openai",
    "sendgrid",
    "turso",
    "elastic cloud",
    "css",
    "dovetail",
    "k6",
    "amazon ec2",
    "yarn",
    "svelte",
    "miro",
    "react router",
    "meilisearch",
    "vercel",
    "authy",
    "tmux",
    "figma",
    "postgresql",
    "mixpanel",
    "sentry",
    "html5",
    "firebase",
    "shopify",
    "tauri",
    "notion",
    "neovim",
    "dgraph",
    "prisma",
    "cypress",
    "formik",
    "drizzle",
]

const SkillsCloud: React.FC = () => (
    <div className="bg-transparent relative flex size-full max-w-lg items-center justify-center overflow-hidden rounded-lg px-20 pb-20 pt-8">
        <IconCloud iconSlugs={SKILLS_SLUGS} />
    </div>
)

export { SkillsCloud }
export default SkillsCloud
